version: '3'
services:
  vplan-viso:
    build: .
    image: drjume/vplan-viso
    container_name: vplan-viso
    environment:
      - TZ=Europe/Berlin
    ports:
      - "8080:8000"
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/vplan-viso/share:/opt/vplan-viso/share