version: '3'
services:
  vplan-viso:
    build: .
    image: drjume/vplan-viso:0.6.1
    container_name: vplan-viso
    environment:
      - TZ=Europe/Berlin
    ports:
      - "8080:3000"
    restart: unless-stopped
    volumes:
      - /opt/vplan-viso/share:/app/share