version: '3.2'
services:
  vplan-viso:
    build: .
    image: drjume/vplan-viso:master
    container_name: vplan-viso
    environment:
      - TZ=Europe/Berlin
    ports:
      - target: 3000
        published: 8080
    restart: unless-stopped
    volumes:
      - /opt/vplan-viso/share:/app/share