version: '3.5'
services:
  vplan-viso:
    build: .
    image: drjume/vplan-viso:master
    container_name: vplan-viso
    environment:
      - TZ=Europe/Berlin
    ports:
      - target: 3000
        published: 8080
    restart: unless-stopped
    volumes:
      - /opt/vplan-viso/share:/app/share
    networks:
      - vplan-viso

networks:
  vplan-viso:
    name: vplan-viso
