version: '3.5'
services:
  vplan-viso:
    image: drjume/vplan-viso:{{VERSION}}
    container_name: vplan-viso-{{VERSION}}
    environment:
      - TZ=Europe/Berlin
    ports:
      - target: 3000
        published: 8080 # externer Port
    restart: unless-stopped
    volumes: # HOST:CONTAINER
      - /opt/vplan-viso/share:/app/share
    networks:
      - vplan-viso

networks:
  vplan-viso:
    name: vplan-viso
