version: '3.5'
services:
  vplan-viso:
    image: drjume/vplan-viso:{{VERSION}}
    container_name: vplan-viso
    environment:
      - TZ=Europe/Berlin
    ports:
      - target: 3000
        published: ${VPLAN_VISO_PORT} # externer Port
    restart: unless-stopped
    volumes: # HOST:CONTAINER
      - ${VPLAN_VISO_VOLUME}:/app/share
    networks:
      - vplan-viso

networks:
  vplan-viso:
    name: vplan-viso
