version: '3'
services:
  vplan-viso:
    image: drjume/vplan-viso:{{VERSION}}
    container_name: vplan-viso-{{VERSION}}
    environment:
      - TZ=Europe/Berlin
    ports:
      - "8080:3000"
    restart: unless-stopped
    volumes:
      - /opt/vplan-viso/share:/app/share