version: '3.2'
services:
  vplan-viso:
    image: drjume/vplan-viso:{{VERSION}}
    container_name: vplan-viso-{{VERSION}}
    environment:
      - TZ=Europe/Berlin
    ports:
      - target: 3000
        published: 8080
    restart: unless-stopped
    volumes:
      - /opt/vplan-viso/share:/app/share